server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 200166
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    base-package: com.example.login.entity
    servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 2MB
  mail:
    username: 1197994090@qq.com
    password: nazzftetszutbace # 授权码
    host: smtp.qq.com  # SMTP服务器（根据邮箱类型修改）
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      example:
        login: DEBUG
    org:
      springframework:
        security: INFO

# 头像上传配置
avatar:
  upload:
    path: D:/test_python/uploads/avatars/
  access:
    url-prefix: http://localhost:8080/avatars/

cors:
  allowed-origins: http://localhost:5173

